app_name: fastapi-book-project
repo_url: git@github.com:actokuyt/fastapi-book-project.git
app_dir: /var/www/{{app_name}}/html
logs_dir: /var/www/{{app_name}}/logs
clone_dir: /home/{{ ansible_user }}/{{app_name}}
domain_name: 3.255.165.252
app_port: 8000
http_port: 80
